### ISSUE TITLE
Convert *.mat to *.json

### ISSUE THREAD

**Issue by tensorboy** [leonid-pishchulin/poseval#1]
Dear Leonid,
       I'm a master student interested in taking part in the PoseTrack Challenge, and I found your code is best for the evaluation of that task.
       However, the official website only provided the *.mat version of the labels not *.json format your code is using, and some keys like "img_idx" the *.mat version seems didn't provide. 
      It would be greatly helpful if you can give me information about how to get the *.json format label. :)

I really appreciate your work!
Thank you!

**Comment by tensorboy** [comment]
After dive deep in the code, I got deeper understanding of it. 
But still helpful if you have an example. :)

Best Regards,
Wangpeng

**Comment by leonid-pishchulin** [comment]
updated README.md and added mat -> json conversion code

**Comment by tensorboy** [comment]
Thank you very much!
Best,
Wangpeng
