### ISSUE TITLE
MOT Error if a sequence doesnt have a particular limb

### ISSUE THREAD

**Issue by soulslicer** [leonid-pishchulin/poseval#12]
[17839_mpii_relpath_5sec_testsub (copy).txt](https://github.com/leonid-pishchulin/poseval/files/2129189/17839_mpii_relpath_5sec_testsub.copy.txt)

You can attempt to run the evaluation of this file against itself. It will crash immediately. Why is this the case? Immediate debugging will tell you that the MOT Accumlator events is empty.

>   File "evaluate.py", line 68, in <module>
>     main()
>   File "evaluate.py", line 54, in main
>     metricsAll = evaluateTracking(gtFramesAll,prFramesAll)
>   File "/media/raaj/Storage/video_datasets/posetrack_valscripts/py/evaluateTracking.py", line 134, in evaluateTracking
>     metricsAll = computeMetrics(gtFramesAll, motAll)
>   File "/media/raaj/Storage/video_datasets/posetrack_valscripts/py/evaluateTracking.py", line 95, in computeMetrics
>     metricsMid = mh.compute(accAll[i], metrics=metricsMidNames, return_dataframe=False, name='acc')
>   File "/usr/local/lib/python2.7/dist-packages/motmetrics/metrics.py", line 127, in compute
>     df = df.events
>   File "/usr/local/lib/python2.7/dist-packages/motmetrics/mot.py", line 231, in events
>     self.cached_events_df = MOTAccumulator.new_event_dataframe_with_data(self._indices, self._events)
>   File "/usr/local/lib/python2.7/dist-packages/motmetrics/mot.py", line 271, in new_event_dataframe_with_data
>     raw_type = pd.Categorical(tevents[0], categories=['RAW', 'FP', 'MISS', 'SWITCH', 'MATCH'], ordered=False)
> IndexError: list index out of rang

        totalJ = [0]*nJoints

        for j in range(len(imgidxs)):
            imgidx = imgidxs[j,0]
            # iterate over joints
            for i in range(nJoints):
                # GT tracking ID
                trackidxGT = motAll[imgidx][i]["trackidxGT"]
                # prediction tracking ID
                trackidxPr = motAll[imgidx][i]["trackidxPr"]
                # distance GT <-> pred part to compute MOT metrics
                # 'NaN' means force no match
                dist = motAll[imgidx][i]["dist"]
                # Call update once per frame
                #if si == 25:
                if len(trackidxGT): totalJ[i] += 1
                accAll[i].update(
                    trackidxGT,                 # Ground truth objects in this frame
                    trackidxPr,                 # Detector hypotheses in this frame
                    dist                        # Distances from objects to hypotheses
                )

        print totalJ

Will give [0, 0, 34, 34, 0, 0, 0, 0, 34, 34, 34, 34, 34, 34, 34], and it crashes. But some datasets in posetrack dont have leg poses for example. Thats how the ground truth is. So why is it crashing???

**Comment by leonid-pishchulin** [comment]
I just published a fix that should address your problem, see https://github.com/leonid-pishchulin/poseval/commit/0268b263c82a61fd4758826746f4012cdf22da71
