### ISSUE TITLE
GT frames only consist of frames with annotations during evaluation

### ISSUE THREAD

**Issue by wjbKimberly** [leonid-pishchulin/poseval#19]
It seems that when convert gt annoations to 2017 format. 
In the function to_old in [convert.py](https://github.com/leonid-pishchulin/poseval/blob/master/py/convert.py) 129 line.

The predictions will have result with all of the frames in one video, but the groundTruth only consider cases with annotations. So it may occur following error:

`
Traceback (most recent call last):
  File "evaluate.py", line 72, in <module>
    main()
  File "evaluate.py", line 32, in main
    gtFramesAll,prFramesAll = eval_helpers.load_data_dir(argv)
  File "/poseval/py/eval_helpers.py", line 407, in load_data_dir
    raise Exception('# prediction frames %d <> # GT frames %d for %s' % (len(pr),len(gt),predFilename))
Exception: # prediction frames 117 <> # GT frames 52 for /001735_mpii_test.json

`

**Comment by leonid-pishchulin** [comment]
you have to provide predictions for the full set of GT sequences, no matter if some of the GT sequences do not have annotations. Then, evaluation script will only consider prediction sequences for which GT keypoints exist, and ignore the rest of the prediction sequences.

**Comment by leonid-pishchulin** [comment]
you have to provide predictions in the same format as the ground truth. So if GT is in posetrack18 format then predictions must be in the same posetrack18 format.
