### ISSUE TITLE
Prediction json

### ISSUE THREAD

**Issue by chnanc001** [leonid-pishchulin/poseval#21]
is it possible to get a set of prediction json files that correspond with the annotated val json files for testing purposes?

**Comment by leonid-pishchulin** [comment]
if you would like to extract a list of files with annotated keypoints, you can run the following script
mkdir posetrack18-val-keypoints
`m=0;for f in val/*json; do n=$(cat $f | grep keypoints | wc -l); if [ $n -gt 1 ]; then cp -v $f posetrack18-val-keypoints; m=$(($m+1)); fi;  done; echo $m`

**Comment by leonid-pishchulin** [comment]
disregard my previous message as it will only work for the properly formatted json. the best way to check if json has annotated keypoints is to write a python script. Below is a sketch for the posetrack18 format:

def check_has_keypoints(a):
    if 'keypoints' in a:
        for x in a['keypoints']:
            if x > 0:
                return True

    return False

if __name__ == "__main__":
    fname = 'file.json'
    json_data = json.load(open(fname, 'r'))
    if 'annotations' in json_data:
        for a in json_data['annotations']:
            bAnnotated = check_has_keypoints(a)
            break
    print(bAnnotated)
