### ISSUE TITLE
different evaluate result using different format

### ISSUE THREAD

**Issue by leoxiaobin** [leonid-pishchulin/poseval#23]
hi, @leonid-pishchulin ,

the evaluate code can support 2018 format and 2017 format, but I find that using different format I can get different results in some situation. To investigate the issue, I use only one video sequence, and only two frames's ground truth and prediction results.

Use ground truth of 2017 format and prediction of 2017 format, I got the result:
```
Average Precision (AP) metric:
& Head & Shou & Elb  & Wri  & Hip  & Knee & Ankl & Total\\
& 94.4 & 83.3 &100.0 &100.0 &100.0 & 90.0 & 77.5 & 92.3 \\
``` 

Use ground truth of 2018 format and prediction of 2018 format, I got the result:
```
Evaluation of per-frame multi-person pose estimation
saving results to ./out/total_AP_metrics.json
Average Precision (AP) metric:
& Head & Shou & Elb  & Wri  & Hip  & Knee & Ankl & Total\\
& 33.3 & 37.5 & 37.5 & 50.0 & 37.5 & 50.0 & 37.5 & 40.0 \\
```

I have upload my test json at https://drive.google.com/open?id=1jfNa75EKAIMHd8TUrOGp44XxXYANLUm9

**Comment by leonid-pishchulin** [comment]
do you use the tip of the mainline evaluation code?

**Comment by leoxiaobin** [comment]
@leonid-pishchulin ,yes, I am using the newest code.

**Comment by leoxiaobin** [comment]
@leonid-pishchulin , I also uploaded the test json as https://drive.google.com/open?id=1jfNa75EKAIMHd8TUrOGp44XxXYANLUm9. You could also test it.

**Comment by leonid-pishchulin** [comment]
I checked your json files https://drive.google.com/open?id=1jfNa75EKAIMHd8TUrOGp44XxXYANLUm9
gt_18 and pred_18 have 2 annotated and predicted people; gt_17 and pred_17 have 5 annotated and predicted people. Thus, results might be different

**Comment by leonid-pishchulin** [comment]
I had to fix a bug in conversion script where scores were not converted properly, https://github.com/leonid-pishchulin/poseval/commit/0d8c001e1c64096a74f2f471966268d09dae0fe1
could you verify if this solves your issue? If not you can compare the the gt 2017 vs. gt 2018 after conversion https://github.com/leonid-pishchulin/poseval/blob/master/py/eval_helpers.py#L386 and pred 2017 vs. pred 2018 after conversion https://github.com/leonid-pishchulin/poseval/blob/master/py/eval_helpers.py#L407
if they are the same then the result must be the same

**Comment by leoxiaobin** [comment]
hi, @leonid-pishchulin , I have tried the latest code, it not solves this issue.

I have tried another experiment, using the gt 2017 as ground truth input, and gt 2018 as prediction result input, I got the result:

Average Precision (AP) metric:
```
& Head & Shou & Elb  & Wri  & Hip  & Knee & Ankl & Total\\
&100.0 &100.0 &100.0 &100.0 &100.0 &100.0 &100.0 &100.0 \\
```
Multiple Object Tracking (MOT) metrics:
```
& MOTA & MOTA & MOTA & MOTA & MOTA & MOTA & MOTA & MOTA & MOTP & Prec & Rec  \\
& Head & Shou & Elb  & Wri  & Hip  & Knee & Ankl & Total& Total& Total& Total\\
&100.0 &100.0 &100.0 &100.0 &100.0 &100.0 &100.0 &100.0 &100.0 &100.0 &100.0 \\
```

So it's weird that if I get different results when using gt 2017 and gt 2018 as ground truth input.

I have tried more video sequences, not all the sequences get different results, only some sequences get different results.

**Comment by wjbKimberly** [comment]
Hi, I run command as follows:
`
python evaluate.py   --groundTruth=../../posetrack_check/gt_18/ --predictions=../../posetrack_check/pre_18/ --evalPoseTracking   --evalPoseEstimation
`
It still throws the exception due to the mismatching number of gt frames and predict frames:
```
Namespace(evalPoseEstimation=True, evalPoseTracking=True, groundTruth='../../posetrack_check/gt_18/', outputDir='./out', predictions='../../posetrack_check/pre_18/', saveEvalPerSequence=False)
Loading data
INFO:convert:Detected PoseTrack18 format. Converting to 2017...
INFO:convert:Detected PoseTrack18 format. Converting to 2017...
Traceback (most recent call last):
  File "evaluate.py", line 72, in <module>
    main()
  File "evaluate.py", line 32, in main
    gtFramesAll,prFramesAll = eval_helpers.load_data_dir(argv)
  File "/var/storage/shared/pnrsy/t-jiwan/poseval/py/eval_helpers.py", line 409, in load_data_dir
    raise Exception('# prediction frames %d <> # GT frames %d for %s' % (len(pr),len(gt),predFilename))
Exception: # prediction frames 117 <> # GT frames 52 for ../../posetrack_check/pre_18/001735_mpii_test.json
```

@leoxiaobin  Did you fix the bug with my pull request? Anyone submit the result successfully?

**Comment by classner** [comment]
Hi @leoxiaobin, @wjbKimberly,

I investigated this issue further and identified and fixed a number of problems that led to this issue (see PR #25 linked above). I verified with the sequence @wjbKimberly provided, thanks a lot for this sample.

Apologies for the inconvenience; should you run into further problems with this please let us know!

**Comment by leonid-pishchulin** [comment]
merged this PR. @leoxiaobin, @wjbKimberly: please pull from the mainline and let us know if it fixes your problems

**Comment by wjbKimberly** [comment]
The bug has been fixed, thanks for quick reply.
As @leoxiaobin shows, using new evaluate code, the result has significantly change ( MOTA from 10.3 to 41.8). This is consistent with my test result on the entire validation set. Using new evaluate code, result on 2018 validation dataset has improved 5 points! But I don't know how much it will change on test dataset.
Could you please send the new result on test dataset to us again using new evaluate code? Since previous submission which not considering "ignore_regions" mask may confused us.
