### ISSUE TITLE
Some picture's ground truths have problem.

### ISSUE THREAD

**Issue by ArchNew** [leonid-pishchulin/poseval#29]
![42dabcc9110c589bda04fde77e0050c](https://user-images.githubusercontent.com/11910381/45013534-fdb0e880-b04d-11e8-99ad-b2abbab42c77.png)
I don't think this picture should have such two keypoints as ground truths.

the image name is: 'images/bonn_mpii_test_v2_5sec/17839_mpii/00000143.jpg'
the annotation file contains its ground truth is: 17839_mpii_relpath_5sec_testsub.mat

This is the one that I spotted, I don't know if there are more of them.

**Comment by leonid-pishchulin** [comment]
while there might be some annotation noise, such cases are extremely rare. This particular case is probably due to interpolation that is used during annotation of bounding boxes. Evaluation is however performed using annotated poses that are labeled manually.
