### ISSUE TITLE
Posetrack 2018

### ISSUE THREAD

**Issue by soulslicer** [leonid-pishchulin/poseval#31]
Good day,

My code currently automatically converts the Posetrack 2018 results into exactly the Posetrack 2017 format (same evaluation as last year)

So I have this format basically:

> 
> POSETRACK_MAPPING = dict()
> POSETRACK_MAPPING["RANKLE"] = 0
> POSETRACK_MAPPING["RKNEE"] = 1
> POSETRACK_MAPPING["RHIP"] = 2
> POSETRACK_MAPPING["LHIP"] = 3
> POSETRACK_MAPPING["LKNEE"] = 4
> POSETRACK_MAPPING["LANKLE"] = 5
> POSETRACK_MAPPING["RWRIST"] = 6
> POSETRACK_MAPPING["RELBOW"] = 7
> POSETRACK_MAPPING["RSHOULDER"] = 8
> POSETRACK_MAPPING["LSHOULDER"] = 9
> POSETRACK_MAPPING["LELBOW"] = 10
> POSETRACK_MAPPING["LWRIST"] = 11
> POSETRACK_MAPPING["NECK"] = 12
> POSETRACK_MAPPING["NOSE"] = 13 # Have nose
> POSETRACK_MAPPING["TOP"] = 14
> 

If so, will this still work? Have you changed anything in your code that might affect this?

Also, are you evaluating the ears at all then?

**Comment by Odaimoko** [comment]
Hi. Could you tell me where can I find annotations of PoseTrack 2018? The anno on the download page is 2017 ver.

**Comment by leonid-pishchulin** [comment]
@soulslicer evaluation code automatically converts to posetrack2017 format, if needed, prior to evaluation. Evaluation of ears is not performed.

**Comment by soulslicer** [comment]
Thats unfortunate, i have already generated my posetrack2018 results in the posetrack2017 format. Is there a way I can test it on the website without converting it back again

**Comment by leonid-pishchulin** [comment]
if you can evaluate locally using the evaluation tools, you should be able to evaluate on server as well.
