### ISSUE TITLE
Question about annotations of PoseTrack2018

### ISSUE THREAD

**Issue by Odaimoko** [leonid-pishchulin/poseval#32]
In the [download page](https://posetrack.net/users/download.php), annotation data contains only 250 videos for training and 50 for validation. But there are 792 and 170 image sequences for training and validation respectively(375 for test). Where can I get the rest annotations? Besides the 2018 annotation contains the same videos as those in 2017 annotation which seems strange. After I registerd, I could not find addtional annotaions either.

**Comment by leonid-pishchulin** [comment]
you have to go to posetrack.net, login and click 'data' to get to the download page. There you will find Posetrack 2018 and 2017 datasets

**Comment by Odaimoko** [comment]
Yeah, but the annotations are missed? I cant find them on this page.

**Comment by leonid-pishchulin** [comment]
please write an email to admin@posetrack.net to clarify the issue.
