### ISSUE TITLE
About the metrics, is 20% of the head bounding box diagnoal or 30%

### ISSUE THREAD

**Issue by ArchNew** [leonid-pishchulin/poseval#33]
I'm confused. In your 2017 paper, it is 20%. But in your 2018 paper, it is 30%.And this site, the source code appears to use 30% version.

**Comment by leonid-pishchulin** [comment]
head_size is defined as 0.6*diagonal. 
https://github.com/leonid-pishchulin/poseval/blob/master/py/eval_helpers.py#L77
Distance threshold used for keypoint matching is 0.5*head_size
