### ISSUE TITLE
Is the 'name' of 'image' really needed in evaluation process?

### ISSUE THREAD

**Issue by ArchNew** [leonid-pishchulin/poseval#34]
If I'm reading the source code correctly, it seems 'name' of the 'image' is not necessary for the evaluation process. I'm having trouble to reconcile the result from the validation set and the result from the test server. There is too big a gap between those two.

**Comment by leonid-pishchulin** [comment]
you have to submit results in the same format as the ground truth for *all* frames of each GT sequence, not only for those that are annotated. I know about another case where a user saw big difference between test and val set when submitting results for annotated frames only, not for all frames.
