### ISSUE TITLE
Submit the test set result for posetrack2018 and posetrack2017

### ISSUE THREAD

**Issue by Airpooyan** [leonid-pishchulin/poseval#35]
I have ran all my experiments on posetrack2018 validation set and posetrack2017 validation set
Now I want to submit the test set result. Does the posetrack2018 test set consists of all the posetrack2017 test set?
If I submit the posetrack2018 result, could you please feed me back with both posetrack2018 and posetrack2017(for comparision with others) test set result?

**Comment by Airpooyan** [comment]
When I run the convert.py to convert the posetrack2017 format json files to  posetrack2018 format, it shows that some videos not exist. I passed these videos and thus only have 210 converted test videos.
![image](https://user-images.githubusercontent.com/18299981/48245820-c8e35800-e427-11e8-8ebf-2880c6c60b6f.png)

**Comment by leonid-pishchulin** [comment]
while posetrack 2018 test set is a superset of posetrack 2017 test set, you have to submit to posetrack 2017 challenge separately from posetrack 2018 challenge. Submission to 2017 challenge can be done using posetrack 2017 annotation format, while submission to 2018 challenge can be done using 2018 format.

**Comment by Airpooyan** [comment]
Thanks for your reply.
But as you see, when I convert the test sequences of the 214 videos for posetrack2017 test set to 2018 format, some of the video sequences don't exist(such as (1,1), (1,3), (1,4), (1,5), (1,7732), (1,9611), (1,11204)).How can I deal with these video sequences?

**Comment by Airpooyan** [comment]
![image](https://user-images.githubusercontent.com/18299981/48298352-f0552600-e4f6-11e8-9b2d-4ac490255f98.png)
In the poseflow code I find this, I think I know what happened to the unmatched video sequences......
Please fix this bug if you could.
Thanks very much

**Comment by Airpooyan** [comment]
![image](https://user-images.githubusercontent.com/18299981/48298494-593d9d80-e4f9-11e8-840f-beec5dc430dd.png)
The json of 2017 test sequences is converted from the original .mat files.
When I ran the convery.py code , it reported 'Assertion Error'. Then I changed the code of posetrack18_id2fname.py in this place. Finally I found some '(seqtype_idx, seqidx)' didn't exist in the sequences index.

**Comment by leonid-pishchulin** [comment]
in order to submit to posetrack 2017 you don't need to convert to 2018, but use 2017 format. You need to provide results for all test sequences in posetrack 2017 datset.

**Comment by Airpooyan** [comment]
Seems that I can only do like you say
Thanks very much
