### ISSUE TITLE
about the Neck

### ISSUE THREAD

**Issue by lianuo** [leonid-pishchulin/poseval#40]
after I run the evaluate.py  for my result of posetrack2018 val ,
I got the result of pose estimation, but I found the keypoint "neck" in the Item of "names",
while in the  posetrack2018 val ,there is no neck keypoint , how this value come from? it is very low compare with other values

**Comment by lianuo** [comment]
These are defination of key points  in posetrack2018 
"keypoints": ["nose", "head_bottom", "head_top", "left_ear", "right_ear", "left_shoulder", "right_shoulder", "left_elbow", "right_elbow", "left_wrist", "right_wrist", "left_hip", "right_hip", "left_knee", "right_knee", "left_ankle", "right_ankle"]

**Comment by lianuo** [comment]
is the Neck means head_bottom? haha ,maybe

**Comment by pchsu-hsupc** [comment]
Hi @lianuo ,

So should we change the item "neck" to "head_bottom" right ?
