### ISSUE TITLE
MOT Error not solved

### ISSUE THREAD

**Issue by frankchen121212** [leonid-pishchulin/poseval#42]
Hi, the closed issue "mot error on 1 Jul 2018" seem to be unfixed 
when running the following 3 videos ->017839_mpii_test , 004707_mpii_test ,004712_mpii_test
error occured
![2019-03-25 15-39-26屏幕截图](https://user-images.githubusercontent.com/22726349/54902401-41990b80-4f14-11e9-9350-adce7e2dbec6.png)

Also when I use ground truth as result running single video 
Estimation result of 004707_mpii_test 
& Head & Shou & Elb  & Wri  & Hip  & Knee & Ankl & Total\\
&100.0 &100.0 &100.0 &100.0 &100.0 &  0.0 &  0.0 & 73.3 \\

Estimation result of 004712_mpii_test 
& Head & Shou & Elb  & Wri  & Hip  & Knee & Ankl & Total\\
&100.0 &100.0 &100.0 &100.0 &100.0 &  0.0 &  0.0 & 73.3 \\

Estimation result of 017839_mpii_test 
& Head & Shou & Elb  & Wri  & Hip  & Knee & Ankl & Total\\
&100.0 &100.0 & 50.0 & 50.0 &100.0 &  0.0 &  0.0 & 60.0 \\

Could you please look into that?

**Comment by frankchen121212** [comment]
I also submitted the result file of the tree videos : 004707, 004712, 017839
[error_json.zip](https://github.com/leonid-pishchulin/poseval/files/3002067/error_json.zip)

**Comment by frankchen121212** [comment]
The poseval version I downloaded  was on 11 Nov 2018

**Comment by lxtGH** [comment]
@frankchen121212 Hi I met the same problem, Do you solve it now??

**Comment by frankchen121212** [comment]
> @frankchen121212 Hi I met the same problem, Do you solve it now??

I haven't solved it yet, you may email him @leonid-pishchulin .

**Comment by lxtGH** [comment]
@frankchen121212 I solved it. Please install motmetrics 1.0.2  pip install motmetrics==1.0.2

**Comment by frankchen121212** [comment]
> @frankchen121212 I solved it. Please install motmetrics 1.0.2 by pip install motmetrics==1.0.2

Thank you very much for your kind assistance~I'll try it 
Have a nice day :)
