### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by yataoz** [leonid-pishchulin/poseval#9]
Hi, I tried evaluating my model on the validation set using evaluate.py. Everything went well and there wasn't any errors, but the output seemed wrong. I event got negative numbers and NaN (see below). I have no idea what is going wrong. Can someone share some thoughts? 

& MOTA & MOTA & MOTA & MOTA & MOTA & MOTA & MOTA & MOTA & MOTP & Prec & Rec  \\
& Head & Shou & Elb  & Wri  & Hip  & Knee & Ankl & Total& Total& Total& Total\\
&-61.0 &-98.8 &-94.0 &-78.9 &-98.6 &-86.8 &-79.9 &-83.8 & 61.3 &  nan &  0.7 \\

**Comment by yataoz** [comment]
Closed the issue here. Just found a bug in my own code.

**Comment by SonNNguyen** [comment]
> Closed the issue here. Just found a bug in my own code.

Hi @yataoz I got the same error as yours. Also my AP is 0 all. Maybe your own code error have some common with mine which I couldnt find it yet. Could you share your bug with me? Thank you very much
